POST http://localhost:3002/api/persons
Content-Type: application/json

{
    "name": "John Doe",
    "number": "1136547656"
}

###

POST http://localhost:3002/api/persons
Content-Type: application/json

{

}

###

POST http://localhost:3002/api/persons
Content-Type: application/json

{
    "name": "Walter White"
}

###

POST http://localhost:3002/api/persons
Content-Type: application/json

{
    "number": "1136549874"
}